[project]
name = "platformer-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcade>=3.0.1",
]
[tool.mypy]
strict = true
